version: '3'
services:
  db:
    image: mysql:5.7.22
    ports:
    - "3301:3301"
    container_name: report6-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: report6
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: java_db
  java:
    container_name: report6-java
    build: .
    volumes:
    - .:/report6
    ports:
      - "8000:8000"
    links:
    - db


